title: Glaserei Butzen
email: info@glasbutzen.de
author: Thomas Butzen
keywords: glaserei butzen, glaserei, butzen
description: .
url: "http://glasbutzen.de"

collections:
  downloads:
    output: true

# Build settings
markdown: kramdown

# Sass configuration
sass:
  style: compressed
gems:
  - normalize-scss
  - support-for
