title: Glaserei Butzen
email: info@glasbutzen.de
author: Thomas Butzen
description: Ganzglasduschen, Reparaturverglasung, Spiegel und mehr
keywords:
- glaserei butzen
- glaserei nettetal
- glaserei
- butzen
- nettetal
- glasduschen
- schleiferei
- spiegel
- isolierglas
- ganzglastüren
- küchenrückwände
- duschkabinen
- sandstrahlarbeiten
- u.v. kleben
- sicherheitsgläser
- clearShield
- balkonverglasung
- treppengeländer
- schaufensterscheiben
- feuerfestes Glas
- ornamentgläser
- flachglas
- kunstverglasung
- überdachungen
- türendesign
- fliegengitter
url: "http://glasbutzen.de"

collections:
  downloads:
    output: true

# Build settings
markdown: kramdown
encoding: utf-8
exclude: ['Gemfile', 'Gemfile.lock']

gems:
- jekyll-compass
- jekyll-email-protect
