title: Glaserei Butzen
email: info@glasbutzen.de
author: Thomas Butzen
keywords: glaserei butzen, glaserei, butzen
description: .
url: "http://glasbutzen.de"

collections:
  downloads:
    output: true

# Build settings
markdown: kramdown
encoding: utf-8
exclude: ['Gemfile', 'Gemfile.lock']

gems:
- jekyll-compass
- jekyll-email-protect
